{{- if .Values.installHttpbin }}
apiVersion: v1
kind: Pod
metadata:
  name: httpbin
  namespace: {{ .Release.Namespace }}
  labels:
    app: httpbin
spec:
  containers:
  - name: httpbin
    image: kennethreitz/httpbin
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: httpbin
  ports:
  - port: 80
{{- end }}
