{{- if .Values.filters.healthcheck.enable -}}
apiVersion: enroute.saaras.io/v1
kind: HttpFilter
metadata:
  labels:
    app: {{ .Values.service.name }}-app
  name: {{ .Values.service.name }}-{{ .Values.service.port }}-healthcheckfilter
  namespace: {{ .Release.Namespace }}
spec:
  name: {{ .Values.service.name }}-{{ .Values.service.port }}-healtcheck
  type: http_filter_healthcheck 
  httpFilterConfig:
    config: |
         {
             "path" : "/healthz"
         }
{{- end -}}
