---
apiVersion: enroute.saaras.io/v1
kind: GatewayHost
metadata:
  name: {{ include "service-policy.fullname" . }}
  labels:
    {{- include "service-policy.labels" . | nindent 4 }}-gatewayhost
  namespace: {{ .Release.Namespace }}
spec:
  virtualhost:
    {{- if eq (len .Values.fqdn) 0 }}
    fqdn: '*'
    {{- else }}
    fqdn: {{ quote .Values.fqdn }}
    {{- end -}}
  routes:
    {{- range .Values.routes }}
    - conditions:
      {{- range .conditions }}
      - prefix: {{ .prefix }}
      {{- end }}
      services:
      {{- range .services }}
      - name: {{ .name }}
        port: {{ .port | int }}
        {{- if .healthcheck.enabled }}
          healthCheck:
            healthyThresholdCount: {{ .services.healthcheck.healthy | default 3 }}
            intervalSeconds: {{ .services.healthcheck.interval | default 5 }}
            path: {{ .services.healthcheck.path }}
            host: {{ .services.healthcheck.host }}
            timeoutSeconds: {{ .services.healthcheck.timeout | default 3 }}
            unhealthyThresholdCount: {{ .services.healthcheck.unhealthy | default 3 }}
        {{- end }}
      {{- end }}
    {{- end }}
