{{- if or (eq .Values.serviceAccount.create true) (eq .Values.enrouteService.rbac.create true) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "enroute.serviceAccountName" . }}
  labels:
    {{- include "enroute.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
