{
 "title": "Enroute API Gateway Stats",
 "description": "Round Trip Time/Cluster Health/Request Level Stats",
 "tags": [
  "enroute-universal-api-gateway",
  "enroute-gw",
  "saaras",
  "envoy"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster_name",
    "query": "metrics(envoy_cluster.*circuit_breakers_default_cx_open)"
   }
  ]
 },
 "panels": [
  {
   "title": "${cluster_name} Response Time (Enroute <-> Server) Histogram",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Request Count" }
   ],
   "targets": [
    {
     "expr": "sum(increase  (envoy_cluster_${cluster_name}_internal_upstream_rq_time_bucket[30s])) by (le)",
     "legendFormat": "{{le}} ms"
    }
   ]
  },
  {
   "title": "${cluster_name} Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_${cluster_name}_upstream_rq_total{}[1m]))  "
    }
   ]
  },
  {
   "title": "${cluster_name} Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_${cluster_name}_internal_upstream_rq_xx{envoy_response_code_class=\"2\"}[1m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(envoy_cluster_${cluster_name}_internal_upstream_rq_xx{envoy_response_code_class=\"4\"}[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(envoy_cluster_${cluster_name}_internal_upstream_rq_xx{envoy_response_code_class=\"5\"}[1m]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(increase(envoy_cluster_${cluster_name}_internal_upstream_rq_xx{envoy_response_code_class=\"3\"}[1m]))",
     "legendFormat": "3xx"
    }
   ]
  },
  {
   "title": "Pool ${cluster_name} Member Count",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(envoy_cluster_${cluster_name}_membership_total{})"
    }
   ]
  },
  {
   "title": "Pool ${cluster_name} Member Change",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(envoy_cluster_${cluster_name}_membership_change{})"
    }
   ]
  },
  {
   "title": "Pool ${cluster_name} Member Healthy",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(envoy_cluster_${cluster_name}_membership_healthy{})"
    }
   ]
  },
  {
   "title": "Pool ${cluster_name} Member Degraded",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(envoy_cluster_${cluster_name}_membership_degraded{})"
    }
   ]
  },
  {
   "title": "Downstream Total active requests rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq_total{}[1m])) ",
     "legendFormat": "{{}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 17 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    { "expr": "avg(envoy_server_uptime{})" }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 17 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_allocated{})"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 17 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_heap_size{})"
    }
   ]
  },
  {
   "title": "Downstream Total active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active{}) "
    }
   ]
  }
 ]
}